### ISSUE TITLE
Bad Credentials Error

### ISSUE THREAD

**Issue by ramyaramdasan** [elranu/Github-PR-tasks#5]
Hi, 

I have added this task to a pipeline, but I receive the following error for a repository whose Access settings are intact. I have other pipelines on the same repository performing similar tasks, and they all work without any such error:

2020-11-09T11:20:13.6531402Z ##[section]Starting: Create pull request
2020-11-09T11:20:13.8201637Z ==============================================================================
2020-11-09T11:20:13.8202420Z Task         : Create a Github Pull request
2020-11-09T11:20:13.8202848Z Description  : Create a Github Pull request
2020-11-09T11:20:13.8203080Z Version      : 1.0.25
2020-11-09T11:20:13.8205046Z Author       : Mariano Julio Vicario
2020-11-09T11:20:13.8205634Z Help         : Github Pull Request
2020-11-09T11:20:13.8205904Z ==============================================================================
2020-11-09T11:20:15.4963761Z dae54c05-71a5-4970-bdd3-fd8f5cb2f597 exists true
2020-11-09T11:20:15.6706775Z (node:5572) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-11-09T11:20:15.6708232Z (node:5572) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-11-09T11:20:15.6709116Z (node:5572) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-11-09T11:20:15.6710071Z (node:5572) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-11-09T11:20:15.6711185Z (node:5572) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-11-09T11:20:15.6712091Z (node:5572) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-11-09T11:20:15.6712939Z (node:5572) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-11-09T11:20:15.6713831Z (node:5572) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-11-09T11:20:15.6714690Z (node:5572) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-11-09T11:20:15.6715533Z (node:5572) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-11-09T11:20:15.6716391Z (node:5572) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-11-09T11:20:15.6717159Z (node:5572) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-11-09T11:20:15.6718378Z (node:5572) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-11-09T11:20:15.6719297Z (node:5572) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-11-09T11:20:16.0849816Z ##[error]Bad credentials
2020-11-09T11:20:16.0884136Z { HttpError: Bad credentials
2020-11-09T11:20:16.0884994Z     at response.text.then.e (D:\a\_tasks\Create-pull-request_35ceba32-9bd4-415b-a7c7-06f60b1c8668\1.0.25\node_modules\@octokit\request\lib\request.js:55:27)
2020-11-09T11:20:16.0886794Z     at process._tickCallback (internal/process/next_tick.js:109:7)
2020-11-09T11:20:16.0887264Z   name: 'HttpError',
2020-11-09T11:20:16.0904936Z   status: 401,
2020-11-09T11:20:16.0959623Z   headers: 
2020-11-09T11:20:16.0960304Z    { 'access-control-allow-origin': '*',
2020-11-09T11:20:16.0968642Z      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset',
2020-11-09T11:20:16.0971710Z      connection: 'close',
2020-11-09T11:20:16.0982302Z      'content-length': '80',
2020-11-09T11:20:16.0993391Z      'content-security-policy': 'default-src \'none\'',
2020-11-09T11:20:16.0999109Z      'content-type': 'application/json; charset=utf-8',
2020-11-09T11:20:16.0999576Z      date: 'Mon, 09 Nov 2020 11:20:16 GMT',
2020-11-09T11:20:16.1000294Z      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
2020-11-09T11:20:16.1000627Z      server: 'GitHub.com',
2020-11-09T11:20:16.1000856Z      status: '401 Unauthorized',
2020-11-09T11:20:16.1001278Z      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
2020-11-09T11:20:16.1001633Z      vary: 'Accept-Encoding, Accept, X-Requested-With',
2020-11-09T11:20:16.1002231Z      'x-content-type-options': 'nosniff',
2020-11-09T11:20:16.1006075Z      'x-frame-options': 'deny',
2020-11-09T11:20:16.1006395Z      'x-github-media-type': 'github.v3; format=json',
2020-11-09T11:20:16.1006731Z      'x-github-request-id': '0540:03D6:90DD:AACB:5FA925EF',
2020-11-09T11:20:16.1007070Z      'x-ratelimit-limit': '60',
2020-11-09T11:20:16.1009002Z      'x-ratelimit-remaining': '58',
2020-11-09T11:20:16.1009269Z      'x-ratelimit-reset': '1604922045',
2020-11-09T11:20:16.1009523Z      'x-ratelimit-used': '2',
2020-11-09T11:20:16.1009799Z      'x-xss-protection': '1; mode=block' },
2020-11-09T11:20:16.1010023Z   request: 
2020-11-09T11:20:16.1010206Z    { method: 'GET',
2020-11-09T11:20:16.1010555Z      url: 'https://api.github.com/repos/sede-x/sn-ad-october-8/pulls?state=open&head=sede-x%3Adevelop&base=master',
2020-11-09T11:20:16.1010950Z      headers: 
2020-11-09T11:20:16.1011188Z       { accept: 'application/vnd.github.v3+json',
2020-11-09T11:20:16.1011539Z         'user-agent': 'octokit.js/16.15.0 Node.js/6.17.1 (Windows Server 2016; x64)',
2020-11-09T11:20:16.1011899Z         authorization: 'token undefined' },
2020-11-09T11:20:16.1012171Z      request: { validate: [Object] } },
2020-11-09T11:20:16.1015786Z   documentation_url: 'https://docs.github.com/rest' }
2020-11-09T11:20:16.1052046Z ##[section]Finishing: Create pull request

**Comment by ramyaramdasan** [comment]
Can you please help in fixing this error?

Thanks
Ramya

**Comment by ramyaramdasan** [comment]
This issue is fixed. so, closing the issue.
